# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: workflow_dispatch
#on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - run: |
        CURRENT_BUILD_NUM="$(grep -oP 'version="[0-9]+\.\K[0-9]+' generated.txt)"
        NEW_VERSION="$(date +%y%m%d).$((CURRENT_BUILD_NUM+1))"
        sed -i "s/version=.*/version=\"${NEW_VERSION}\",/g" generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add generated.txt
        git commit -m "[skip ci] Bump version to ${NEW_VERSION}"
        git push
        
